### ISSUE TITLE
warnings while running the code

### ISSUE THREAD

**Issue by EaswarDSharma** [kalaspuffar/apache-tika-readdoc#2]
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details`

getting these warnings..

**Comment by kalaspuffar** [comment]
This is because we aren't using that logger. Not anything critical. You should get the error output through other means.
